/**
 * Normalized ASR error taxonomy.
 *
 * Architecture: §9.2 — every concrete `IAsrClient` impl maps provider-specific
 * errors to this small closed set. The UploadQueue and RetryPolicy *only* see
 * `AsrError`; they never branch on HTTP status codes or provider strings.
 * Adding a new provider means writing a new mapping function, not touching the
 * queue.
 */

export type AsrErrorClass =
  | 'network' //  DNS, TCP reset, TLS, connection refused
  | 'timeout' //  HTTP read/write past the configured deadline
  | 'auth' //     401 / 403 — bad key, expired bearer
  | 'rate_limit' //  429 — back off (honors Retry-After in RetryPolicy)
  | 'bad_audio' //   413 / 415 — payload too big / unsupported format
  | 'server_5xx' //  500-599
  | 'client_4xx' //  400, 404, 422, etc. (not auth, not rate_limit, not bad_audio)
  | 'unknown'; //    Catch-all; retried up to maxAttempts then surfaced

/** Normalized error thrown by every `IAsrClient` impl; carries classification + correlation. */
export class AsrError extends Error {
  /** Construct with taxonomy class, message, and optional cause / Retry-After / support id. */
  constructor(
    public readonly kind: AsrErrorClass,
    message: string,
    public override readonly cause?: unknown,
    /**
     * Server-supplied `Retry-After` in milliseconds, if present and parsed.
     * `null` means "no signal — use our own backoff curve."
     */
    public readonly retryAfterMs: number | null = null,
    /**
     * Stable correlation id surfaced to the user on permanent failures
     * ("Error code: ab12cd34"). The string is short and case-insensitive.
     * Generated by the caller, not here, so it can be tied to a job/chunk.
     */
    public readonly supportId?: string,
  ) {
    super(message);
    this.name = 'AsrError';
  }
}

/**
 * Map an HTTP status to the taxonomy. Providers can override (e.g., Groq
 * returns 413 for payload-too-large; OpenAI used to return 400). When in
 * doubt, default to `client_4xx` / `server_5xx` and let RetryPolicy decide.
 */
export function classifyHttpStatus(status: number): AsrErrorClass {
  if (status === 401 || status === 403) return 'auth';
  if (status === 408) return 'timeout';
  if (status === 413 || status === 415) return 'bad_audio';
  if (status === 429) return 'rate_limit';
  if (status >= 500 && status <= 599) return 'server_5xx';
  if (status >= 400 && status <= 499) return 'client_4xx';
  // 1xx/2xx/3xx aren't error statuses; classifying here means a caller bug.
  return 'unknown';
}
